version: '3.8'
services:
  db:
    image: postgis/postgis:17-3.5-alpine
    environment:
      POSTGRES_USER: carparksuser
      POSTGRES_PASSWORD: carparkspassword
      POSTGRES_DB: carparksdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "carparksuser", "-d", "carparksdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  cache:
    image: redis:7.4-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile.native
    environment:
      QUARKUS_DATASOURCE_REACTIVE_URL: vertx-reactive:postgresql://db:5432/carparksdb
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/carparksdb
      QUARKUS_DATASOURCE_USERNAME: carparksuser
      QUARKUS_DATASOURCE_PASSWORD: carparkspassword
      QUARKUS_REDIS_HOSTS: redis://cache:6379
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - app

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  postgres_data:
  grafana_data:
