version: '3.8'
services:
  db:
    image: postgis/postgis:17-3.5-alpine
    environment:
      POSTGRES_USER: carparksuser
      POSTGRES_PASSWORD: carparkspassword
      POSTGRES_DB: carparksdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "carparksuser", "-d", "carparksdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile.native
    environment:
      QUARKUS_DATASOURCE_REACTIVE_URL: vertx-reactive:postgresql://db:5432/carparksdb
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/carparksdb
      QUARKUS_DATASOURCE_USERNAME: carparksuser
      QUARKUS_DATASOURCE_PASSWORD: carparkspassword
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: