global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'carparks-job'
    metrics_path: /q/metrics
    static_configs:
      - targets: ['app:8080']
        labels:
          application: 'carparks-service'
